### 새로운 채팅방 열기
GET http://localhost:8000/chats/{{email}}/rooms/{{new}}/multi-count

> {%
if (response.body && response.body.session_id) {
    client.global.set("uuid", response.body.session_id);
}
client.log("uuid = " + client.global.get("uuid"));
%}

### 기존 대화방 멀티턴 갯수 확인
GET http://localhost:8000/chats/{{email}}/rooms/{{uuid}}/multi-count

### 대화 -> 멀티턴 갯수 + 1
POST http://localhost:8000/chats/{{email}}/rooms/{{uuid}}/multi-count

### 멀티턴 갯수 초기화
POST http://localhost:8000/chats/{{email}}/rooms/{{uuid}}/multi-refresh

### 대화방 삭제
DELETE http://localhost:8000/chats/{{email}}/rooms/{{uuid}}


### 내 대화방 목록 보기
GET http://localhost:8000/chats/{{email}}/room


### 첫 질문하기
POST http://localhost:8000/chats/{{email}}/rooms/{{new}}/stream
Content-Type: application/json

{
  "question": "안녕? 내 이름은 홍길동이야"
}

> {%
if (response.body && response.body.session_id) {
    client.global.set("uuid", response.body.session_id);
}
client.log("uuid = " + client.global.get("uuid"));
%}


### 이어서 질문하기
POST http://localhost:8000/chats/{{email}}/rooms/{{uuid}}/stream
Content-Type: application/json

{
  "question": "오늘 날짜와 요일은 기억하지?"
}

### 채팅 히스토리 불러오기
GET http://localhost:8000/chats/{{email}}/rooms/{{uuid}}

### 채팅 방 및 채팅 내역 모두 삭제
DELETE http://localhost:8000/chats
Content-Type: application/json

{
  "user_email": "{{email}}"
}